/*
SQLyog Enterprise - MySQL GUI v7.02 
MySQL - 5.5.13 : Database - snapypos
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`snapypos` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `snapypos`;

/*Table structure for table `action_history` */

DROP TABLE IF EXISTS `action_history`;

CREATE TABLE `action_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTION_TIME` datetime DEFAULT NULL,
  `ACTION_NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK3F3AF36B3E20AD51` (`USER_ID`),
  CONSTRAINT `FK3F3AF36B3E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

/*Table structure for table `attendence_history` */

DROP TABLE IF EXISTS `attendence_history`;

CREATE TABLE `attendence_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLOCK_IN_TIME` datetime DEFAULT NULL,
  `CLOCK_OUT_TIME` datetime DEFAULT NULL,
  `CLOCK_IN_HOUR` smallint(6) DEFAULT NULL,
  `CLOCK_OUT_HOUR` smallint(6) DEFAULT NULL,
  `CLOCKED_OUT` bit(1) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `SHIFT_ID` int(11) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKDFE829A3E20AD51` (`USER_ID`),
  KEY `FKDFE829A7660A5E3` (`SHIFT_ID`),
  KEY `FKDFE829A2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FKDFE829A2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FKDFE829A3E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FKDFE829A7660A5E3` FOREIGN KEY (`SHIFT_ID`) REFERENCES `shift` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `cash_drawer` */

DROP TABLE IF EXISTS `cash_drawer`;

CREATE TABLE `cash_drawer` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK6221077D2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK6221077D2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `cash_drawer_reset_history` */

DROP TABLE IF EXISTS `cash_drawer_reset_history`;

CREATE TABLE `cash_drawer_reset_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RESET_TIME` datetime DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK719418223E20AD51` (`USER_ID`),
  CONSTRAINT `FK719418223E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `cooking_instruction` */

DROP TABLE IF EXISTS `cooking_instruction`;

CREATE TABLE `cooking_instruction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `coupon_and_discount` */

DROP TABLE IF EXISTS `coupon_and_discount`;

CREATE TABLE `coupon_and_discount` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `BARCODE` varchar(120) DEFAULT NULL,
  `QUALIFICATION_TYPE` int(11) DEFAULT NULL,
  `APPLY_TO_ALL` bit(1) DEFAULT NULL,
  `MINIMUM_BUY` int(11) DEFAULT NULL,
  `MAXIMUM_OFF` int(11) DEFAULT NULL,
  `VALUE` double DEFAULT NULL,
  `EXPIRY_DATE` datetime DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `AUTO_APPLY` bit(1) DEFAULT NULL,
  `MODIFIABLE` bit(1) DEFAULT NULL,
  `NEVER_EXPIRE` bit(1) DEFAULT NULL,
  `UUID` varchar(36) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `currency` */

DROP TABLE IF EXISTS `currency`;

CREATE TABLE `currency` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(20) DEFAULT NULL,
  `NAME` varchar(30) DEFAULT NULL,
  `SYMBOL` varchar(10) DEFAULT NULL,
  `EXCHANGE_RATE` double DEFAULT NULL,
  `DECIMAL_PLACES` int(11) DEFAULT NULL,
  `TOLERANCE` double DEFAULT NULL,
  `BUY_PRICE` double DEFAULT NULL,
  `SALES_PRICE` double DEFAULT NULL,
  `MAIN` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Table structure for table `currency_balance` */

DROP TABLE IF EXISTS `currency_balance`;

CREATE TABLE `currency_balance` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BALANCE` double DEFAULT NULL,
  `CURRENCY_ID` int(11) DEFAULT NULL,
  `CASH_DRAWER_ID` int(11) DEFAULT NULL,
  `DPR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK2CC0E08EFB910735` (`DPR_ID`),
  KEY `FK2CC0E08E9006558` (`CASH_DRAWER_ID`),
  KEY `FK2CC0E08E28DD6C11` (`CURRENCY_ID`),
  CONSTRAINT `FK2CC0E08E28DD6C11` FOREIGN KEY (`CURRENCY_ID`) REFERENCES `currency` (`ID`),
  CONSTRAINT `FK2CC0E08E9006558` FOREIGN KEY (`CASH_DRAWER_ID`) REFERENCES `cash_drawer` (`ID`),
  CONSTRAINT `FK2CC0E08EFB910735` FOREIGN KEY (`DPR_ID`) REFERENCES `drawer_pull_report` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `custom_payment` */

DROP TABLE IF EXISTS `custom_payment`;

CREATE TABLE `custom_payment` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `REQUIRED_REF_NUMBER` bit(1) DEFAULT NULL,
  `REF_NUMBER_FIELD_NAME` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `customer` */

DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
  `AUTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOYALTY_NO` varchar(30) DEFAULT NULL,
  `LOYALTY_POINT` int(11) DEFAULT NULL,
  `SOCIAL_SECURITY_NUMBER` varchar(60) DEFAULT NULL,
  `PICTURE` blob,
  `HOMEPHONE_NO` varchar(30) DEFAULT NULL,
  `MOBILE_NO` varchar(30) DEFAULT NULL,
  `WORKPHONE_NO` varchar(30) DEFAULT NULL,
  `EMAIL` varchar(40) DEFAULT NULL,
  `SALUTATION` varchar(60) DEFAULT NULL,
  `FIRST_NAME` varchar(60) DEFAULT NULL,
  `LAST_NAME` varchar(60) DEFAULT NULL,
  `name` varchar(120) DEFAULT NULL,
  `DOB` varchar(16) DEFAULT NULL,
  `SSN` varchar(30) DEFAULT NULL,
  `ADDRESS` varchar(220) DEFAULT NULL,
  `CITY` varchar(30) DEFAULT NULL,
  `STATE` varchar(30) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `COUNTRY` varchar(30) DEFAULT NULL,
  `VIP` bit(1) DEFAULT NULL,
  `CREDIT_LIMIT` double DEFAULT NULL,
  `CREDIT_SPENT` double DEFAULT NULL,
  `CREDIT_CARD_NO` varchar(30) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `customer_properties` */

DROP TABLE IF EXISTS `customer_properties`;

CREATE TABLE `customer_properties` (
  `id` int(11) NOT NULL,
  `property_value` varchar(255) DEFAULT NULL,
  `property_name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`,`property_name`),
  KEY `FKD43068347BBCCF0` (`id`),
  CONSTRAINT `FKD43068347BBCCF0` FOREIGN KEY (`id`) REFERENCES `customer` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `data_update_info` */

DROP TABLE IF EXISTS `data_update_info`;

CREATE TABLE `data_update_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `delivery_address` */

DROP TABLE IF EXISTS `delivery_address`;

CREATE TABLE `delivery_address` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS` text,
  `PHONE_EXTENSION` varchar(10) DEFAULT NULL,
  `ROOM_NO` varchar(30) DEFAULT NULL,
  `DISTANCE` double DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK29ACA6899E1C3CF1` (`CUSTOMER_ID`),
  CONSTRAINT `FK29ACA6899E1C3CF1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `delivery_charge` */

DROP TABLE IF EXISTS `delivery_charge`;

CREATE TABLE `delivery_charge` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(220) DEFAULT NULL,
  `ZIP_CODE` varchar(20) DEFAULT NULL,
  `START_RANGE` double DEFAULT NULL,
  `END_RANGE` double DEFAULT NULL,
  `CHARGE_AMOUNT` double DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `delivery_configuration` */

DROP TABLE IF EXISTS `delivery_configuration`;

CREATE TABLE `delivery_configuration` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNIT_NAME` varchar(20) DEFAULT NULL,
  `UNIT_SYMBOL` varchar(8) DEFAULT NULL,
  `CHARGE_BY_ZIP_CODE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `delivery_instruction` */

DROP TABLE IF EXISTS `delivery_instruction`;

CREATE TABLE `delivery_instruction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOTES` varchar(220) DEFAULT NULL,
  `CUSTOMER_NO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK29D9CA39E1C3D97` (`CUSTOMER_NO`),
  CONSTRAINT `FK29D9CA39E1C3D97` FOREIGN KEY (`CUSTOMER_NO`) REFERENCES `customer` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `drawer_assigned_history` */

DROP TABLE IF EXISTS `drawer_assigned_history`;

CREATE TABLE `drawer_assigned_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIME` datetime DEFAULT NULL,
  `OPERATION` varchar(60) DEFAULT NULL,
  `A_USER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK5A823C91F1DD782B` (`A_USER`),
  CONSTRAINT `FK5A823C91F1DD782B` FOREIGN KEY (`A_USER`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `drawer_pull_report` */

DROP TABLE IF EXISTS `drawer_pull_report`;

CREATE TABLE `drawer_pull_report` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPORT_TIME` datetime DEFAULT NULL,
  `REG` varchar(15) DEFAULT NULL,
  `TICKET_COUNT` int(11) DEFAULT NULL,
  `BEGIN_CASH` double DEFAULT NULL,
  `NET_SALES` double DEFAULT NULL,
  `SALES_TAX` double DEFAULT NULL,
  `CASH_TAX` double DEFAULT NULL,
  `TOTAL_REVENUE` double DEFAULT NULL,
  `GROSS_RECEIPTS` double DEFAULT NULL,
  `GIFTCERTRETURNCOUNT` int(11) DEFAULT NULL,
  `GIFTCERTRETURNAMOUNT` double DEFAULT NULL,
  `GIFTCERTCHANGEAMOUNT` double DEFAULT NULL,
  `CASH_RECEIPT_NO` int(11) DEFAULT NULL,
  `CASH_RECEIPT_AMOUNT` double DEFAULT NULL,
  `CREDIT_CARD_RECEIPT_NO` int(11) DEFAULT NULL,
  `CREDIT_CARD_RECEIPT_AMOUNT` double DEFAULT NULL,
  `DEBIT_CARD_RECEIPT_NO` int(11) DEFAULT NULL,
  `DEBIT_CARD_RECEIPT_AMOUNT` double DEFAULT NULL,
  `REFUND_RECEIPT_COUNT` int(11) DEFAULT NULL,
  `REFUND_AMOUNT` double DEFAULT NULL,
  `RECEIPT_DIFFERENTIAL` double DEFAULT NULL,
  `CASH_BACK` double DEFAULT NULL,
  `CASH_TIPS` double DEFAULT NULL,
  `CHARGED_TIPS` double DEFAULT NULL,
  `TIPS_PAID` double DEFAULT NULL,
  `TIPS_DIFFERENTIAL` double DEFAULT NULL,
  `PAY_OUT_NO` int(11) DEFAULT NULL,
  `PAY_OUT_AMOUNT` double DEFAULT NULL,
  `DRAWER_BLEED_NO` int(11) DEFAULT NULL,
  `DRAWER_BLEED_AMOUNT` double DEFAULT NULL,
  `DRAWER_ACCOUNTABLE` double DEFAULT NULL,
  `CASH_TO_DEPOSIT` double DEFAULT NULL,
  `VARIANCE` double DEFAULT NULL,
  `DELIVERY_CHARGE` double DEFAULT NULL,
  `totalVoidWst` double DEFAULT NULL,
  `totalVoid` double DEFAULT NULL,
  `totalDiscountCount` int(11) DEFAULT NULL,
  `totalDiscountAmount` double DEFAULT NULL,
  `totalDiscountSales` double DEFAULT NULL,
  `totalDiscountGuest` int(11) DEFAULT NULL,
  `totalDiscountPartySize` int(11) DEFAULT NULL,
  `totalDiscountCheckSize` int(11) DEFAULT NULL,
  `totalDiscountPercentage` double DEFAULT NULL,
  `totalDiscountRatio` double DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `drawer_report_time` (`REPORT_TIME`),
  KEY `FKAEC362203E20AD51` (`USER_ID`),
  KEY `FKAEC362202AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FKAEC362202AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FKAEC362203E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `drawer_pull_report_voidtickets` */

DROP TABLE IF EXISTS `drawer_pull_report_voidtickets`;

CREATE TABLE `drawer_pull_report_voidtickets` (
  `DPREPORT_ID` int(11) NOT NULL,
  `code` int(11) DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `hast` varchar(255) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  KEY `FK98CF9B143EF4CD9B` (`DPREPORT_ID`),
  CONSTRAINT `FK98CF9B143EF4CD9B` FOREIGN KEY (`DPREPORT_ID`) REFERENCES `drawer_pull_report` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `employee_in_out_history` */

DROP TABLE IF EXISTS `employee_in_out_history`;

CREATE TABLE `employee_in_out_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OUT_TIME` datetime DEFAULT NULL,
  `IN_TIME` datetime DEFAULT NULL,
  `OUT_HOUR` smallint(6) DEFAULT NULL,
  `IN_HOUR` smallint(6) DEFAULT NULL,
  `CLOCK_OUT` bit(1) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `SHIFT_ID` int(11) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK6D5DB9FA3E20AD51` (`USER_ID`),
  KEY `FK6D5DB9FA7660A5E3` (`SHIFT_ID`),
  KEY `FK6D5DB9FA2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK6D5DB9FA2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FK6D5DB9FA3E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FK6D5DB9FA7660A5E3` FOREIGN KEY (`SHIFT_ID`) REFERENCES `shift` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `global_config` */

DROP TABLE IF EXISTS `global_config`;

CREATE TABLE `global_config` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `POS_KEY` varchar(60) DEFAULT NULL,
  `POS_VALUE` varchar(220) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `POS_KEY` (`POS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `gratuity` */

DROP TABLE IF EXISTS `gratuity`;

CREATE TABLE `gratuity` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AMOUNT` double DEFAULT NULL,
  `PAID` bit(1) DEFAULT NULL,
  `REFUNDED` bit(1) DEFAULT NULL,
  `TICKET_ID` int(11) DEFAULT NULL,
  `OWNER_ID` int(11) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK34E4E377AA075D69` (`OWNER_ID`),
  KEY `FK34E4E3771DF2D7F1` (`TICKET_ID`),
  KEY `FK34E4E3772AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK34E4E3771DF2D7F1` FOREIGN KEY (`TICKET_ID`) REFERENCES `ticket` (`ID`),
  CONSTRAINT `FK34E4E3772AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FK34E4E377AA075D69` FOREIGN KEY (`OWNER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `group_taxes` */

DROP TABLE IF EXISTS `group_taxes`;

CREATE TABLE `group_taxes` (
  `GROUP_ID` varchar(128) NOT NULL,
  `elt` int(11) NOT NULL,
  KEY `FKF8A37399EFF11066` (`GROUP_ID`),
  KEY `FKF8A37399D900AA01` (`elt`),
  CONSTRAINT `FKF8A37399D900AA01` FOREIGN KEY (`elt`) REFERENCES `tax` (`ID`),
  CONSTRAINT `FKF8A37399EFF11066` FOREIGN KEY (`GROUP_ID`) REFERENCES `tax_group` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `guest_check_print` */

DROP TABLE IF EXISTS `guest_check_print`;

CREATE TABLE `guest_check_print` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TICKET_ID` int(11) DEFAULT NULL,
  `TABLE_NO` varchar(255) DEFAULT NULL,
  `TICKET_TOTAL` double DEFAULT NULL,
  `PRINT_TIME` datetime DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKCE827C6F3E20AD51` (`USER_ID`),
  CONSTRAINT `FKCE827C6F3E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_group` */

DROP TABLE IF EXISTS `inventory_group`;

CREATE TABLE `inventory_group` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_item` */

DROP TABLE IF EXISTS `inventory_item`;

CREATE TABLE `inventory_item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_DATE` datetime DEFAULT NULL,
  `NAME` varchar(60) DEFAULT NULL,
  `PACKAGE_BARCODE` varchar(30) DEFAULT NULL,
  `UNIT_BARCODE` varchar(30) DEFAULT NULL,
  `UNIT_PER_PACKAGE` double DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `PACKAGE_REORDER_LEVEL` int(11) DEFAULT NULL,
  `PACKAGE_REPLENISH_LEVEL` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `AVERAGE_PACKAGE_PRICE` double DEFAULT NULL,
  `TOTAL_UNIT_PACKAGES` double DEFAULT NULL,
  `TOTAL_RECEPIE_UNITS` double DEFAULT NULL,
  `UNIT_PURCHASE_PRICE` double DEFAULT NULL,
  `UNIT_SELLING_PRICE` double DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `PUNIT_ID` int(11) DEFAULT NULL,
  `RECIPE_UNIT_ID` int(11) DEFAULT NULL,
  `ITEM_GROUP_ID` int(11) DEFAULT NULL,
  `ITEM_LOCATION_ID` int(11) DEFAULT NULL,
  `ITEM_VENDOR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK7DC968369E60C333` (`ITEM_VENDOR_ID`),
  KEY `FK7DC968366848D615` (`RECIPE_UNIT_ID`),
  KEY `FK7DC968362CD583C1` (`ITEM_GROUP_ID`),
  KEY `FK7DC968363525E956` (`PUNIT_ID`),
  KEY `FK7DC9683695E455D3` (`ITEM_LOCATION_ID`),
  CONSTRAINT `FK7DC968362CD583C1` FOREIGN KEY (`ITEM_GROUP_ID`) REFERENCES `inventory_group` (`ID`),
  CONSTRAINT `FK7DC968363525E956` FOREIGN KEY (`PUNIT_ID`) REFERENCES `packaging_unit` (`ID`),
  CONSTRAINT `FK7DC968366848D615` FOREIGN KEY (`RECIPE_UNIT_ID`) REFERENCES `packaging_unit` (`ID`),
  CONSTRAINT `FK7DC9683695E455D3` FOREIGN KEY (`ITEM_LOCATION_ID`) REFERENCES `inventory_location` (`ID`),
  CONSTRAINT `FK7DC968369E60C333` FOREIGN KEY (`ITEM_VENDOR_ID`) REFERENCES `inventory_vendor` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_location` */

DROP TABLE IF EXISTS `inventory_location`;

CREATE TABLE `inventory_location` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `WAREHOUSE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK59073B58C46A9C15` (`WAREHOUSE_ID`),
  CONSTRAINT `FK59073B58C46A9C15` FOREIGN KEY (`WAREHOUSE_ID`) REFERENCES `inventory_warehouse` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_meta_code` */

DROP TABLE IF EXISTS `inventory_meta_code`;

CREATE TABLE `inventory_meta_code` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(255) DEFAULT NULL,
  `CODE_TEXT` varchar(255) DEFAULT NULL,
  `CODE_NO` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_transaction` */

DROP TABLE IF EXISTS `inventory_transaction`;

CREATE TABLE `inventory_transaction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANSACTION_DATE` datetime DEFAULT NULL,
  `UNIT_QUANTITY` double DEFAULT NULL,
  `UNIT_PRICE` double DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  `TRAN_TYPE` int(11) DEFAULT NULL,
  `REFERENCE_ID` int(11) DEFAULT NULL,
  `ITEM_ID` int(11) DEFAULT NULL,
  `VENDOR_ID` int(11) DEFAULT NULL,
  `FROM_WAREHOUSE_ID` int(11) DEFAULT NULL,
  `TO_WAREHOUSE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKAF48F43BFF3F328A` (`FROM_WAREHOUSE_ID`),
  KEY `FKAF48F43B5B397C5` (`REFERENCE_ID`),
  KEY `FKAF48F43B96A3D6BF` (`ITEM_ID`),
  KEY `FKAF48F43BEDA09759` (`TO_WAREHOUSE_ID`),
  KEY `FKAF48F43BD152C95F` (`VENDOR_ID`),
  CONSTRAINT `FKAF48F43B5B397C5` FOREIGN KEY (`REFERENCE_ID`) REFERENCES `purchase_order` (`ID`),
  CONSTRAINT `FKAF48F43B96A3D6BF` FOREIGN KEY (`ITEM_ID`) REFERENCES `inventory_item` (`ID`),
  CONSTRAINT `FKAF48F43BD152C95F` FOREIGN KEY (`VENDOR_ID`) REFERENCES `inventory_vendor` (`ID`),
  CONSTRAINT `FKAF48F43BEDA09759` FOREIGN KEY (`TO_WAREHOUSE_ID`) REFERENCES `inventory_warehouse` (`ID`),
  CONSTRAINT `FKAF48F43BFF3F328A` FOREIGN KEY (`FROM_WAREHOUSE_ID`) REFERENCES `inventory_warehouse` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_unit` */

DROP TABLE IF EXISTS `inventory_unit`;

CREATE TABLE `inventory_unit` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SHORT_NAME` varchar(255) DEFAULT NULL,
  `LONG_NAME` varchar(255) DEFAULT NULL,
  `ALT_NAME` varchar(255) DEFAULT NULL,
  `CONV_FACTOR1` varchar(255) DEFAULT NULL,
  `CONV_FACTOR2` varchar(255) DEFAULT NULL,
  `CONV_FACTOR3` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_vendor` */

DROP TABLE IF EXISTS `inventory_vendor`;

CREATE TABLE `inventory_vendor` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `ADDRESS` varchar(120) NOT NULL,
  `CITY` varchar(60) NOT NULL,
  `STATE` varchar(60) NOT NULL,
  `ZIP` varchar(60) NOT NULL,
  `COUNTRY` varchar(60) NOT NULL,
  `EMAIL` varchar(60) NOT NULL,
  `PHONE` varchar(60) NOT NULL,
  `FAX` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `inventory_warehouse` */

DROP TABLE IF EXISTS `inventory_warehouse`;

CREATE TABLE `inventory_warehouse` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `item_order_type` */

DROP TABLE IF EXISTS `item_order_type`;

CREATE TABLE `item_order_type` (
  `MENU_ITEM_ID` int(11) NOT NULL,
  `ORDER_TYPE_ID` int(11) NOT NULL,
  KEY `FKE2B8465789FE23F0` (`MENU_ITEM_ID`),
  KEY `FKE2B846573AC1D2E0` (`ORDER_TYPE_ID`),
  CONSTRAINT `FKE2B846573AC1D2E0` FOREIGN KEY (`ORDER_TYPE_ID`) REFERENCES `order_type` (`ID`),
  CONSTRAINT `FKE2B8465789FE23F0` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `kit_ticket_table_num` */

DROP TABLE IF EXISTS `kit_ticket_table_num`;

CREATE TABLE `kit_ticket_table_num` (
  `kit_ticket_id` int(11) NOT NULL,
  `TABLE_ID` int(11) DEFAULT NULL,
  KEY `FK5696584BB73E273E` (`kit_ticket_id`),
  CONSTRAINT `FK5696584BB73E273E` FOREIGN KEY (`kit_ticket_id`) REFERENCES `kitchen_ticket` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `kitchen_ticket` */

DROP TABLE IF EXISTS `kitchen_ticket`;

CREATE TABLE `kitchen_ticket` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TICKET_ID` int(11) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CLOSE_DATE` datetime DEFAULT NULL,
  `VOIDED` bit(1) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  `SERVER_NAME` varchar(30) DEFAULT NULL,
  `TICKET_TYPE` varchar(20) DEFAULT NULL,
  `PG_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK341CBC275CF1375F` (`PG_ID`),
  CONSTRAINT `FK341CBC275CF1375F` FOREIGN KEY (`PG_ID`) REFERENCES `printer_group` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `kitchen_ticket_item` */

DROP TABLE IF EXISTS `kitchen_ticket_item`;

CREATE TABLE `kitchen_ticket_item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COOKABLE` bit(1) DEFAULT NULL,
  `TICKET_ITEM_ID` int(11) DEFAULT NULL,
  `TICKET_ITEM_MODIFIER_ID` int(11) DEFAULT NULL,
  `MENU_ITEM_CODE` varchar(255) DEFAULT NULL,
  `MENU_ITEM_NAME` varchar(120) DEFAULT NULL,
  `MENU_ITEM_GROUP_ID` int(11) DEFAULT NULL,
  `MENU_ITEM_GROUP_NAME` varchar(120) DEFAULT NULL,
  `QUANTITY` int(11) DEFAULT NULL,
  `FRACTIONAL_QUANTITY` double DEFAULT NULL,
  `FRACTIONAL_UNIT` bit(1) DEFAULT NULL,
  `UNIT_NAME` varchar(20) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `VOIDED` bit(1) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  `KITHEN_TICKET_ID` int(11) DEFAULT NULL,
  `ITEM_ORDER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK1462F02BCB07FAA3` (`KITHEN_TICKET_ID`),
  CONSTRAINT `FK1462F02BCB07FAA3` FOREIGN KEY (`KITHEN_TICKET_ID`) REFERENCES `kitchen_ticket` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `licence_type` */

DROP TABLE IF EXISTS `licence_type`;

CREATE TABLE `licence_type` (
  `ID` int(11) DEFAULT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  `AMOUNT` varchar(10) DEFAULT NULL,
  `A_TYPE` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menu_category` */

DROP TABLE IF EXISTS `menu_category`;

CREATE TABLE `menu_category` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) NOT NULL,
  `TRANSLATED_NAME` varchar(120) DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `BEVERAGE` bit(1) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `BTN_COLOR` int(11) DEFAULT NULL,
  `TEXT_COLOR` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `food_category_visible` (`VISIBLE`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_group` */

DROP TABLE IF EXISTS `menu_group`;

CREATE TABLE `menu_group` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) NOT NULL,
  `TRANSLATED_NAME` varchar(120) DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `BTN_COLOR` int(11) DEFAULT NULL,
  `TEXT_COLOR` int(11) DEFAULT NULL,
  `CATEGORY_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `menugroupvisible` (`VISIBLE`),
  KEY `FK4DC1AB7F2E347FF0` (`CATEGORY_ID`),
  CONSTRAINT `FK4DC1AB7F2E347FF0` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `menu_category` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_item` */

DROP TABLE IF EXISTS `menu_item`;

CREATE TABLE `menu_item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `UNIT_NAME` varchar(20) DEFAULT NULL,
  `TRANSLATED_NAME` varchar(120) DEFAULT NULL,
  `BARCODE` varchar(120) DEFAULT NULL,
  `BUY_PRICE` double NOT NULL,
  `STOCK_AMOUNT` double DEFAULT NULL,
  `PRICE` double NOT NULL,
  `DISCOUNT_RATE` double DEFAULT NULL,
  `VISIBLE` bit(1) DEFAULT NULL,
  `DISABLE_WHEN_STOCK_AMOUNT_IS_ZERO` bit(1) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `BTN_COLOR` int(11) DEFAULT NULL,
  `TEXT_COLOR` int(11) DEFAULT NULL,
  `IMAGE` blob,
  `SHOW_IMAGE_ONLY` bit(1) DEFAULT NULL,
  `FRACTIONAL_UNIT` bit(1) DEFAULT NULL,
  `PIZZA_TYPE` bit(1) DEFAULT NULL,
  `DEFAULT_SELL_PORTION` int(11) DEFAULT NULL,
  `GROUP_ID` int(11) DEFAULT NULL,
  `TAX_GROUP_ID` varchar(128) DEFAULT NULL,
  `RECEPIE` int(11) DEFAULT NULL,
  `PG_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK4CD5A1F35188AA24` (`GROUP_ID`),
  KEY `FK4CD5A1F3F3B77C57` (`RECEPIE`),
  KEY `FK4CD5A1F35EE9F27A` (`TAX_GROUP_ID`),
  KEY `FK4CD5A1F35CF1375F` (`PG_ID`),
  CONSTRAINT `FK4CD5A1F35188AA24` FOREIGN KEY (`GROUP_ID`) REFERENCES `menu_group` (`ID`),
  CONSTRAINT `FK4CD5A1F35CF1375F` FOREIGN KEY (`PG_ID`) REFERENCES `printer_group` (`ID`),
  CONSTRAINT `FK4CD5A1F35EE9F27A` FOREIGN KEY (`TAX_GROUP_ID`) REFERENCES `tax_group` (`ID`),
  CONSTRAINT `FK4CD5A1F3F3B77C57` FOREIGN KEY (`RECEPIE`) REFERENCES `recepie` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_item_properties` */

DROP TABLE IF EXISTS `menu_item_properties`;

CREATE TABLE `menu_item_properties` (
  `MENU_ITEM_ID` int(11) NOT NULL,
  `PROPERTY_VALUE` varchar(100) DEFAULT NULL,
  `PROPERTY_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`MENU_ITEM_ID`,`PROPERTY_NAME`),
  KEY `FKF94186FF89FE23F0` (`MENU_ITEM_ID`),
  CONSTRAINT `FKF94186FF89FE23F0` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menu_item_size` */

DROP TABLE IF EXISTS `menu_item_size`;

CREATE TABLE `menu_item_size` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `TRANSLATED_NAME` varchar(60) DEFAULT NULL,
  `DESCRIPTION` varchar(120) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `SIZE_IN_INCH` double DEFAULT NULL,
  `DEFAULT_SIZE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_item_terminal_ref` */

DROP TABLE IF EXISTS `menu_item_terminal_ref`;

CREATE TABLE `menu_item_terminal_ref` (
  `MENU_ITEM_ID` int(11) NOT NULL,
  `TERMINAL_ID` int(11) NOT NULL,
  KEY `FK9EA1AFC89FE23F0` (`MENU_ITEM_ID`),
  KEY `FK9EA1AFC2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK9EA1AFC2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FK9EA1AFC89FE23F0` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menu_modifier` */

DROP TABLE IF EXISTS `menu_modifier`;

CREATE TABLE `menu_modifier` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) DEFAULT NULL,
  `TRANSLATED_NAME` varchar(120) DEFAULT NULL,
  `PRICE` double DEFAULT NULL,
  `EXTRA_PRICE` double DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `BTN_COLOR` int(11) DEFAULT NULL,
  `TEXT_COLOR` int(11) DEFAULT NULL,
  `ENABLE` bit(1) DEFAULT NULL,
  `FIXED_PRICE` bit(1) DEFAULT NULL,
  `PRINT_TO_KITCHEN` bit(1) DEFAULT NULL,
  `SECTION_WISE_PRICING` bit(1) DEFAULT NULL,
  `PIZZA_MODIFIER` bit(1) DEFAULT NULL,
  `GROUP_ID` int(11) DEFAULT NULL,
  `TAX_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `modifierenabled` (`ENABLE`),
  KEY `FK59B6B1B72501CB2C` (`GROUP_ID`),
  KEY `FK59B6B1B7A4802F83` (`TAX_ID`),
  CONSTRAINT `FK59B6B1B72501CB2C` FOREIGN KEY (`GROUP_ID`) REFERENCES `menu_modifier_group` (`ID`),
  CONSTRAINT `FK59B6B1B7A4802F83` FOREIGN KEY (`TAX_ID`) REFERENCES `tax` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_modifier_group` */

DROP TABLE IF EXISTS `menu_modifier_group`;

CREATE TABLE `menu_modifier_group` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `TRANSLATED_NAME` varchar(60) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `EXCLUSIVED` bit(1) DEFAULT NULL,
  `REQUIRED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `mg_enable` (`ENABLED`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

/*Table structure for table `menu_modifier_properties` */

DROP TABLE IF EXISTS `menu_modifier_properties`;

CREATE TABLE `menu_modifier_properties` (
  `MENU_MODIFIER_ID` int(11) NOT NULL,
  `PROPERTY_VALUE` varchar(100) DEFAULT NULL,
  `PROPERTY_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`MENU_MODIFIER_ID`,`PROPERTY_NAME`),
  KEY `FK1273B4BBB79C6270` (`MENU_MODIFIER_ID`),
  CONSTRAINT `FK1273B4BBB79C6270` FOREIGN KEY (`MENU_MODIFIER_ID`) REFERENCES `menu_modifier` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menucategory_discount` */

DROP TABLE IF EXISTS `menucategory_discount`;

CREATE TABLE `menucategory_discount` (
  `DISCOUNT_ID` int(11) NOT NULL,
  `MENUCATEGORY_ID` int(11) NOT NULL,
  KEY `FK4F8523E38D9EA931` (`MENUCATEGORY_ID`),
  KEY `FK4F8523E3D3E91E11` (`DISCOUNT_ID`),
  CONSTRAINT `FK4F8523E38D9EA931` FOREIGN KEY (`MENUCATEGORY_ID`) REFERENCES `menu_category` (`ID`),
  CONSTRAINT `FK4F8523E3D3E91E11` FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `coupon_and_discount` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menugroup_discount` */

DROP TABLE IF EXISTS `menugroup_discount`;

CREATE TABLE `menugroup_discount` (
  `DISCOUNT_ID` int(11) NOT NULL,
  `MENUGROUP_ID` int(11) NOT NULL,
  KEY `FKE3790E40113BF083` (`MENUGROUP_ID`),
  KEY `FKE3790E40D3E91E11` (`DISCOUNT_ID`),
  CONSTRAINT `FKE3790E40113BF083` FOREIGN KEY (`MENUGROUP_ID`) REFERENCES `menu_group` (`ID`),
  CONSTRAINT `FKE3790E40D3E91E11` FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `coupon_and_discount` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menuitem_discount` */

DROP TABLE IF EXISTS `menuitem_discount`;

CREATE TABLE `menuitem_discount` (
  `DISCOUNT_ID` int(11) NOT NULL,
  `MENUITEM_ID` int(11) NOT NULL,
  KEY `FKD89CCDEE33662891` (`MENUITEM_ID`),
  KEY `FKD89CCDEED3E91E11` (`DISCOUNT_ID`),
  CONSTRAINT `FKD89CCDEE33662891` FOREIGN KEY (`MENUITEM_ID`) REFERENCES `menu_item` (`ID`),
  CONSTRAINT `FKD89CCDEED3E91E11` FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `coupon_and_discount` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menuitem_modifiergroup` */

DROP TABLE IF EXISTS `menuitem_modifiergroup`;

CREATE TABLE `menuitem_modifiergroup` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MIN_QUANTITY` int(11) DEFAULT NULL,
  `MAX_QUANTITY` int(11) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `MODIFIER_GROUP` int(11) DEFAULT NULL,
  `MENUITEM_MODIFIERGROUP_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK312B355B7F2F368` (`MODIFIER_GROUP`),
  KEY `FK312B355B6E7B8B68` (`MENUITEM_MODIFIERGROUP_ID`),
  CONSTRAINT `FK312B355B6E7B8B68` FOREIGN KEY (`MENUITEM_MODIFIERGROUP_ID`) REFERENCES `menu_item` (`ID`),
  CONSTRAINT `FK312B355B7F2F368` FOREIGN KEY (`MODIFIER_GROUP`) REFERENCES `menu_modifier_group` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

/*Table structure for table `menuitem_pizzapirce` */

DROP TABLE IF EXISTS `menuitem_pizzapirce`;

CREATE TABLE `menuitem_pizzapirce` (
  `MENU_ITEM_ID` int(11) NOT NULL,
  `PIZZA_PRICE_ID` int(11) NOT NULL,
  KEY `FK17BD51A089FE23F0` (`MENU_ITEM_ID`),
  KEY `FK17BD51A0AE5D580` (`PIZZA_PRICE_ID`),
  CONSTRAINT `FK17BD51A089FE23F0` FOREIGN KEY (`MENU_ITEM_ID`) REFERENCES `menu_item` (`ID`),
  CONSTRAINT `FK17BD51A0AE5D580` FOREIGN KEY (`PIZZA_PRICE_ID`) REFERENCES `pizza_price` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menuitem_shift` */

DROP TABLE IF EXISTS `menuitem_shift`;

CREATE TABLE `menuitem_shift` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SHIFT_PRICE` double DEFAULT NULL,
  `SHIFT_ID` int(11) DEFAULT NULL,
  `MENUITEM_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKE03C92D533662891` (`MENUITEM_ID`),
  KEY `FKE03C92D57660A5E3` (`SHIFT_ID`),
  CONSTRAINT `FKE03C92D533662891` FOREIGN KEY (`MENUITEM_ID`) REFERENCES `menu_item` (`ID`),
  CONSTRAINT `FKE03C92D57660A5E3` FOREIGN KEY (`SHIFT_ID`) REFERENCES `shift` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `menumodifier_pizzamodifierprice` */

DROP TABLE IF EXISTS `menumodifier_pizzamodifierprice`;

CREATE TABLE `menumodifier_pizzamodifierprice` (
  `MENUMODIFIER_ID` int(11) NOT NULL,
  `PIZZAMODIFIERPRICE_ID` int(11) NOT NULL,
  KEY `FK572726F374BE2C71` (`PIZZAMODIFIERPRICE_ID`),
  KEY `FK572726F3AE3F2E91` (`MENUMODIFIER_ID`),
  CONSTRAINT `FK572726F374BE2C71` FOREIGN KEY (`PIZZAMODIFIERPRICE_ID`) REFERENCES `pizza_modifier_price` (`ID`),
  CONSTRAINT `FK572726F3AE3F2E91` FOREIGN KEY (`MENUMODIFIER_ID`) REFERENCES `menu_modifier` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `modifier_multiplier_price` */

DROP TABLE IF EXISTS `modifier_multiplier_price`;

CREATE TABLE `modifier_multiplier_price` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRICE` double DEFAULT NULL,
  `MULTIPLIER_ID` varchar(20) DEFAULT NULL,
  `MENUMODIFIER_ID` int(11) DEFAULT NULL,
  `PIZZA_MODIFIER_PRICE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK8A1609939C9E4883` (`PIZZA_MODIFIER_PRICE_ID`),
  KEY `FK8A160993AE3F2E91` (`MENUMODIFIER_ID`),
  KEY `FK8A16099391D62C51` (`MULTIPLIER_ID`),
  CONSTRAINT `FK8A16099391D62C51` FOREIGN KEY (`MULTIPLIER_ID`) REFERENCES `multiplier` (`NAME`),
  CONSTRAINT `FK8A1609939C9E4883` FOREIGN KEY (`PIZZA_MODIFIER_PRICE_ID`) REFERENCES `pizza_modifier_price` (`ID`),
  CONSTRAINT `FK8A160993AE3F2E91` FOREIGN KEY (`MENUMODIFIER_ID`) REFERENCES `menu_modifier` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `multiplier` */

DROP TABLE IF EXISTS `multiplier`;

CREATE TABLE `multiplier` (
  `NAME` varchar(20) NOT NULL,
  `TICKET_PREFIX` varchar(20) DEFAULT NULL,
  `RATE` double DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `DEFAULT_MULTIPLIER` bit(1) DEFAULT NULL,
  `MAIN` bit(1) DEFAULT NULL,
  `BTN_COLOR` int(11) DEFAULT NULL,
  `TEXT_COLOR` int(11) DEFAULT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `order_type` */

DROP TABLE IF EXISTS `order_type`;

CREATE TABLE `order_type` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) NOT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `SHOW_TABLE_SELECTION` bit(1) DEFAULT NULL,
  `SHOW_GUEST_SELECTION` bit(1) DEFAULT NULL,
  `SHOULD_PRINT_TO_KITCHEN` bit(1) DEFAULT NULL,
  `PREPAID` bit(1) DEFAULT NULL,
  `CLOSE_ON_PAID` bit(1) DEFAULT NULL,
  `REQUIRED_CUSTOMER_DATA` bit(1) DEFAULT NULL,
  `DELIVERY` bit(1) DEFAULT NULL,
  `SHOW_ITEM_BARCODE` bit(1) DEFAULT NULL,
  `SHOW_IN_LOGIN_SCREEN` bit(1) DEFAULT NULL,
  `CONSOLIDATE_TIEMS_IN_RECEIPT` bit(1) DEFAULT NULL,
  `ALLOW_SEAT_BASED_ORDER` bit(1) DEFAULT NULL,
  `HIDE_ITEM_WITH_EMPTY_INVENTORY` bit(1) DEFAULT NULL,
  `HAS_FORHERE_AND_TOGO` bit(1) DEFAULT NULL,
  `PRE_AUTH_CREDIT_CARD` bit(1) DEFAULT NULL,
  `BAR_TAB` bit(1) DEFAULT NULL,
  `RETAIL_ORDER` bit(1) DEFAULT NULL,
  `SHOW_PRICE_ON_BUTTON` bit(1) DEFAULT NULL,
  `SHOW_STOCK_COUNT_ON_BUTTON` bit(1) DEFAULT NULL,
  `SHOW_UNIT_PRICE_IN_TICKET_GRID` bit(1) DEFAULT NULL,
  `PROPERTIES` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `organization_details` */

DROP TABLE IF EXISTS `organization_details`;

CREATE TABLE `organization_details` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(120) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(60) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(60) DEFAULT NULL,
  `ADDRESS_LINE3` varchar(60) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `TELEPHONE` varchar(16) DEFAULT NULL,
  `CNAME` varchar(20) DEFAULT NULL,
  `CSYMBOL` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=335764188 DEFAULT CHARSET=latin1;

/*Table structure for table `packaging_unit` */

DROP TABLE IF EXISTS `packaging_unit`;

CREATE TABLE `packaging_unit` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(30) DEFAULT NULL,
  `SHORT_NAME` varchar(10) DEFAULT NULL,
  `FACTOR` double DEFAULT NULL,
  `BASEUNIT` bit(1) DEFAULT NULL,
  `DIMENSION` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `payment_type` */

DROP TABLE IF EXISTS `payment_type`;

CREATE TABLE `payment_type` (
  `ID` int(11) NOT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `payout_reasons` */

DROP TABLE IF EXISTS `payout_reasons`;

CREATE TABLE `payout_reasons` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REASON` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `payout_recepients` */

DROP TABLE IF EXISTS `payout_recepients`;

CREATE TABLE `payout_recepients` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `pizza_crust` */

DROP TABLE IF EXISTS `pizza_crust`;

CREATE TABLE `pizza_crust` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `TRANSLATED_NAME` varchar(60) DEFAULT NULL,
  `DESCRIPTION` varchar(120) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `DEFAULT_CRUST` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `pizza_modifier_price` */

DROP TABLE IF EXISTS `pizza_modifier_price`;

CREATE TABLE `pizza_modifier_price` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_SIZE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKD3DE7E7896183657` (`ITEM_SIZE`),
  CONSTRAINT `FKD3DE7E7896183657` FOREIGN KEY (`ITEM_SIZE`) REFERENCES `menu_item_size` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `pizza_price` */

DROP TABLE IF EXISTS `pizza_price`;

CREATE TABLE `pizza_price` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRICE` double DEFAULT NULL,
  `MENU_ITEM_SIZE` int(11) DEFAULT NULL,
  `CRUST` int(11) DEFAULT NULL,
  `ORDER_TYPE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKEAC11292DD545B77` (`MENU_ITEM_SIZE`),
  KEY `FKEAC11292A56D141C` (`ORDER_TYPE`),
  KEY `FKEAC112927C59441D` (`CRUST`),
  CONSTRAINT `FKEAC112927C59441D` FOREIGN KEY (`CRUST`) REFERENCES `pizza_crust` (`ID`),
  CONSTRAINT `FKEAC11292A56D141C` FOREIGN KEY (`ORDER_TYPE`) REFERENCES `order_type` (`ID`),
  CONSTRAINT `FKEAC11292DD545B77` FOREIGN KEY (`MENU_ITEM_SIZE`) REFERENCES `menu_item_size` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `printer_configuration` */

DROP TABLE IF EXISTS `printer_configuration`;

CREATE TABLE `printer_configuration` (
  `ID` int(11) NOT NULL,
  `RECEIPT_PRINTER` varchar(255) DEFAULT NULL,
  `KITCHEN_PRINTER` varchar(255) DEFAULT NULL,
  `PRWTS` bit(1) DEFAULT NULL,
  `PRWTP` bit(1) DEFAULT NULL,
  `PKWTS` bit(1) DEFAULT NULL,
  `PKWTP` bit(1) DEFAULT NULL,
  `UNPFT` bit(1) DEFAULT NULL,
  `UNPFK` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `printer_group` */

DROP TABLE IF EXISTS `printer_group`;

CREATE TABLE `printer_group` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `IS_DEFAULT` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `printer_group_printers` */

DROP TABLE IF EXISTS `printer_group_printers`;

CREATE TABLE `printer_group_printers` (
  `printer_id` int(11) NOT NULL,
  `PRINTER_NAME` varchar(255) DEFAULT NULL,
  KEY `FKC05B805E5F31265C` (`printer_id`),
  CONSTRAINT `FKC05B805E5F31265C` FOREIGN KEY (`printer_id`) REFERENCES `printer_group` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `purchase_order` */

DROP TABLE IF EXISTS `purchase_order`;

CREATE TABLE `purchase_order` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` varchar(30) DEFAULT NULL,
  `NAME` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `recepie` */

DROP TABLE IF EXISTS `recepie`;

CREATE TABLE `recepie` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_ITEM` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK6B4E177764931EFC` (`MENU_ITEM`),
  CONSTRAINT `FK6B4E177764931EFC` FOREIGN KEY (`MENU_ITEM`) REFERENCES `menu_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `recepie_item` */

DROP TABLE IF EXISTS `recepie_item`;

CREATE TABLE `recepie_item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERCENTAGE` double DEFAULT NULL,
  `INVENTORY_DEDUCTABLE` bit(1) DEFAULT NULL,
  `INVENTORY_ITEM` int(11) DEFAULT NULL,
  `RECEPIE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK855626DBCAE89B83` (`RECEPIE_ID`),
  KEY `FK855626DB1682B10E` (`INVENTORY_ITEM`),
  CONSTRAINT `FK855626DB1682B10E` FOREIGN KEY (`INVENTORY_ITEM`) REFERENCES `inventory_item` (`ID`),
  CONSTRAINT `FK855626DBCAE89B83` FOREIGN KEY (`RECEPIE_ID`) REFERENCES `recepie` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `restaurant` */

DROP TABLE IF EXISTS `restaurant`;

CREATE TABLE `restaurant` (
  `ID` int(11) NOT NULL,
  `UNIQUE_ID` varchar(20) DEFAULT NULL,
  `NAME` varchar(120) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(60) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(60) DEFAULT NULL,
  `ADDRESS_LINE3` varchar(60) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `TELEPHONE` varchar(16) DEFAULT NULL,
  `CAPACITY` int(11) DEFAULT NULL,
  `TABLES` int(11) DEFAULT NULL,
  `CNAME` varchar(20) DEFAULT NULL,
  `CSYMBOL` varchar(10) DEFAULT NULL,
  `SC_PERCENTAGE` double DEFAULT NULL,
  `GRATUITY_PERCENTAGE` double DEFAULT NULL,
  `TICKET_FOOTER` varchar(60) DEFAULT NULL,
  `PRICE_INCLUDES_TAX` bit(1) DEFAULT NULL,
  `ALLOW_MODIFIER_MAX_EXCEED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shift` */

DROP TABLE IF EXISTS `shift`;

CREATE TABLE `shift` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `START_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `SHIFT_LEN` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `shop_floor` */

DROP TABLE IF EXISTS `shop_floor`;

CREATE TABLE `shop_floor` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `OCCUPIED` bit(1) DEFAULT NULL,
  `IMAGE` mediumblob,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shop_floor_template` */

DROP TABLE IF EXISTS `shop_floor_template`;

CREATE TABLE `shop_floor_template` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) DEFAULT NULL,
  `DEFAULT_FLOOR` bit(1) DEFAULT NULL,
  `MAIN` bit(1) DEFAULT NULL,
  `FLOOR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKBA6EFBD68979C3CD` (`FLOOR_ID`),
  CONSTRAINT `FKBA6EFBD68979C3CD` FOREIGN KEY (`FLOOR_ID`) REFERENCES `shop_floor` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shop_floor_template_properties` */

DROP TABLE IF EXISTS `shop_floor_template_properties`;

CREATE TABLE `shop_floor_template_properties` (
  `id` int(11) NOT NULL,
  `property_value` varchar(60) DEFAULT NULL,
  `property_name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`,`property_name`),
  KEY `FKD70C313CA36AB054` (`id`),
  CONSTRAINT `FKD70C313CA36AB054` FOREIGN KEY (`id`) REFERENCES `shop_floor_template` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shop_table` */

DROP TABLE IF EXISTS `shop_table`;

CREATE TABLE `shop_table` (
  `ID` int(11) NOT NULL,
  `VERSION_NO` bigint(20) NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(60) DEFAULT NULL,
  `CAPACITY` int(11) DEFAULT NULL,
  `X` int(11) DEFAULT NULL,
  `Y` int(11) DEFAULT NULL,
  `FLOOR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK2458E9258979C3CD` (`FLOOR_ID`),
  CONSTRAINT `FK2458E9258979C3CD` FOREIGN KEY (`FLOOR_ID`) REFERENCES `shop_floor` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shop_table_status` */

DROP TABLE IF EXISTS `shop_table_status`;

CREATE TABLE `shop_table_status` (
  `ID` int(11) NOT NULL,
  `VERSION_NO` bigint(20) NOT NULL,
  `TABLE_STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `shop_table_type` */

DROP TABLE IF EXISTS `shop_table_type`;

CREATE TABLE `shop_table_type` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(120) DEFAULT NULL,
  `NAME` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `table_booking_info` */

DROP TABLE IF EXISTS `table_booking_info`;

CREATE TABLE `table_booking_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FROM_DATE` datetime DEFAULT NULL,
  `TO_DATE` datetime DEFAULT NULL,
  `GUEST_COUNT` int(11) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  `PAYMENT_STATUS` varchar(30) DEFAULT NULL,
  `BOOKING_CONFIRM` varchar(30) DEFAULT NULL,
  `BOOKING_CHARGE` double DEFAULT NULL,
  `REMAINING_BALANCE` double DEFAULT NULL,
  `PAID_AMOUNT` double DEFAULT NULL,
  `BOOKING_ID` varchar(30) DEFAULT NULL,
  `BOOKING_TYPE` varchar(30) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fromDate` (`FROM_DATE`),
  KEY `toDate` (`TO_DATE`),
  KEY `FK301C4DE53E20AD51` (`user_id`),
  KEY `FK301C4DE59E1C3CF1` (`customer_id`),
  CONSTRAINT `FK301C4DE53E20AD51` FOREIGN KEY (`user_id`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FK301C4DE59E1C3CF1` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `table_booking_mapping` */

DROP TABLE IF EXISTS `table_booking_mapping`;

CREATE TABLE `table_booking_mapping` (
  `BOOKING_ID` int(11) NOT NULL,
  `TABLE_ID` int(11) NOT NULL,
  KEY `FK6BC51417160DE3B1` (`BOOKING_ID`),
  KEY `FK6BC51417DC46948D` (`TABLE_ID`),
  CONSTRAINT `FK6BC51417160DE3B1` FOREIGN KEY (`BOOKING_ID`) REFERENCES `table_booking_info` (`ID`),
  CONSTRAINT `FK6BC51417DC46948D` FOREIGN KEY (`TABLE_ID`) REFERENCES `shop_table` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `table_ticket_num` */

DROP TABLE IF EXISTS `table_ticket_num`;

CREATE TABLE `table_ticket_num` (
  `SHOP_TABLE_STATUS_ID` int(11) NOT NULL,
  `TICKET_ID` int(11) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `USER_NAME` varchar(30) DEFAULT NULL,
  KEY `FKCBEFF0E454031EC1` (`SHOP_TABLE_STATUS_ID`),
  CONSTRAINT `FKCBEFF0E454031EC1` FOREIGN KEY (`SHOP_TABLE_STATUS_ID`) REFERENCES `shop_table_status` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `table_type_relation` */

DROP TABLE IF EXISTS `table_type_relation`;

CREATE TABLE `table_type_relation` (
  `TABLE_ID` int(11) NOT NULL,
  `TYPE_ID` int(11) NOT NULL,
  KEY `FK93802290F5D6E47B` (`TYPE_ID`),
  KEY `FK93802290DC46948D` (`TABLE_ID`),
  CONSTRAINT `FK93802290DC46948D` FOREIGN KEY (`TABLE_ID`) REFERENCES `shop_table` (`ID`),
  CONSTRAINT `FK93802290F5D6E47B` FOREIGN KEY (`TYPE_ID`) REFERENCES `shop_table_type` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `tax` */

DROP TABLE IF EXISTS `tax`;

CREATE TABLE `tax` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `RATE` double DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `tax_group` */

DROP TABLE IF EXISTS `tax_group`;

CREATE TABLE `tax_group` (
  `ID` varchar(128) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `terminal` */

DROP TABLE IF EXISTS `terminal`;

CREATE TABLE `terminal` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(60) DEFAULT NULL,
  `TERMINAL_KEY` varchar(120) DEFAULT NULL,
  `OPENING_BALANCE` double DEFAULT NULL,
  `CURRENT_BALANCE` double DEFAULT NULL,
  `HAS_CASH_DRAWER` bit(1) DEFAULT NULL,
  `IN_USE` bit(1) DEFAULT NULL,
  `ACTIVE` bit(1) DEFAULT NULL,
  `LOCATION` text,
  `FLOOR_ID` int(11) DEFAULT NULL,
  `ASSIGNED_USER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKE83D827C969C6DE` (`ASSIGNED_USER`),
  CONSTRAINT `FKE83D827C969C6DE` FOREIGN KEY (`ASSIGNED_USER`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `terminal_printers` */

DROP TABLE IF EXISTS `terminal_printers`;

CREATE TABLE `terminal_printers` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  `PRINTER_NAME` varchar(60) DEFAULT NULL,
  `VIRTUAL_PRINTER_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK99EDE5FCC433E65A` (`VIRTUAL_PRINTER_ID`),
  KEY `FK99EDE5FC2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK99EDE5FC2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FK99EDE5FCC433E65A` FOREIGN KEY (`VIRTUAL_PRINTER_ID`) REFERENCES `virtual_printer` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket` */

DROP TABLE IF EXISTS `ticket`;

CREATE TABLE `ticket` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSION_NO` bigint(20) NOT NULL,
  `GLOBAL_ID` varchar(16) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `CLOSING_DATE` datetime DEFAULT NULL,
  `ACTIVE_DATE` datetime DEFAULT NULL,
  `DELIVEERY_DATE` datetime DEFAULT NULL,
  `CREATION_HOUR` int(11) DEFAULT NULL,
  `PAID` bit(1) DEFAULT NULL,
  `VOIDED` bit(1) DEFAULT NULL,
  `VOID_REASON` varchar(255) DEFAULT NULL,
  `WASTED` bit(1) DEFAULT NULL,
  `REFUNDED` bit(1) DEFAULT NULL,
  `SETTLED` bit(1) DEFAULT NULL,
  `DRAWER_RESETTED` bit(1) DEFAULT NULL,
  `SUB_TOTAL` double DEFAULT NULL,
  `TOTAL_DISCOUNT` double DEFAULT NULL,
  `TOTAL_TAX` double DEFAULT NULL,
  `TOTAL_PRICE` double DEFAULT NULL,
  `PAID_AMOUNT` double DEFAULT NULL,
  `DUE_AMOUNT` double DEFAULT NULL,
  `ADVANCE_AMOUNT` double DEFAULT NULL,
  `ADJUSTMENT_AMOUNT` double DEFAULT NULL,
  `NUMBER_OF_GUESTS` int(11) DEFAULT NULL,
  `STATUS` varchar(30) DEFAULT NULL,
  `BAR_TAB` bit(1) DEFAULT NULL,
  `IS_TAX_EXEMPT` bit(1) DEFAULT NULL,
  `IS_RE_OPENED` bit(1) DEFAULT NULL,
  `SERVICE_CHARGE` double DEFAULT NULL,
  `DELIVERY_CHARGE` double DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `DELIVERY_ADDRESS` varchar(120) DEFAULT NULL,
  `CUSTOMER_PICKEUP` bit(1) DEFAULT NULL,
  `DELIVERY_EXTRA_INFO` varchar(255) DEFAULT NULL,
  `TICKET_TYPE` varchar(20) DEFAULT NULL,
  `SHIFT_ID` int(11) DEFAULT NULL,
  `OWNER_ID` int(11) DEFAULT NULL,
  `DRIVER_ID` int(11) DEFAULT NULL,
  `GRATUITY_ID` int(11) DEFAULT NULL,
  `VOID_BY_USER` int(11) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GLOBAL_ID` (`GLOBAL_ID`),
  KEY `creationHour` (`CREATION_HOUR`),
  KEY `ticketpaid` (`PAID`),
  KEY `ticketactiveDate` (`ACTIVE_DATE`),
  KEY `ticketcreateDate` (`CREATE_DATE`),
  KEY `ticketsettled` (`SETTLED`),
  KEY `deliveryDate` (`DELIVEERY_DATE`),
  KEY `ticketclosingDate` (`CLOSING_DATE`),
  KEY `drawerresetted` (`DRAWER_RESETTED`),
  KEY `ticketvoided` (`VOIDED`),
  KEY `FK937B5F0CF575C7D4` (`DRIVER_ID`),
  KEY `FK937B5F0CAA075D69` (`OWNER_ID`),
  KEY `FK937B5F0C7660A5E3` (`SHIFT_ID`),
  KEY `FK937B5F0CC188EA51` (`GRATUITY_ID`),
  KEY `FK937B5F0C1F6A9A4A` (`VOID_BY_USER`),
  KEY `FK937B5F0C2AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FK937B5F0C1F6A9A4A` FOREIGN KEY (`VOID_BY_USER`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FK937B5F0C2AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FK937B5F0C7660A5E3` FOREIGN KEY (`SHIFT_ID`) REFERENCES `shift` (`ID`),
  CONSTRAINT `FK937B5F0CAA075D69` FOREIGN KEY (`OWNER_ID`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FK937B5F0CC188EA51` FOREIGN KEY (`GRATUITY_ID`) REFERENCES `gratuity` (`ID`),
  CONSTRAINT `FK937B5F0CF575C7D4` FOREIGN KEY (`DRIVER_ID`) REFERENCES `users` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_discount` */

DROP TABLE IF EXISTS `ticket_discount`;

CREATE TABLE `ticket_discount` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCOUNT_ID` int(11) DEFAULT NULL,
  `NAME` varchar(30) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `AUTO_APPLY` bit(1) DEFAULT NULL,
  `MINIMUM_AMOUNT` int(11) DEFAULT NULL,
  `VALUE` double DEFAULT NULL,
  `TICKET_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK1FA465141DF2D7F1` (`TICKET_ID`),
  CONSTRAINT `FK1FA465141DF2D7F1` FOREIGN KEY (`TICKET_ID`) REFERENCES `ticket` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item` */

DROP TABLE IF EXISTS `ticket_item`;

CREATE TABLE `ticket_item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) DEFAULT NULL,
  `ITEM_COUNT` int(11) DEFAULT NULL,
  `ITEM_QUANTITY` double DEFAULT NULL,
  `ITEM_NAME` varchar(120) DEFAULT NULL,
  `ITEM_UNIT_NAME` varchar(20) DEFAULT NULL,
  `GROUP_NAME` varchar(120) DEFAULT NULL,
  `CATEGORY_NAME` varchar(120) DEFAULT NULL,
  `ITEM_PRICE` double DEFAULT NULL,
  `ITEM_TAX_RATE` double DEFAULT NULL,
  `SUB_TOTAL` double DEFAULT NULL,
  `SUB_TOTAL_WITHOUT_MODIFIERS` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `TAX_AMOUNT` double DEFAULT NULL,
  `TAX_AMOUNT_WITHOUT_MODIFIERS` double DEFAULT NULL,
  `TOTAL_PRICE` double DEFAULT NULL,
  `TOTAL_PRICE_WITHOUT_MODIFIERS` double DEFAULT NULL,
  `BEVERAGE` bit(1) DEFAULT NULL,
  `INVENTORY_HANDLED` bit(1) DEFAULT NULL,
  `PRINT_TO_KITCHEN` bit(1) DEFAULT NULL,
  `TREAT_AS_SEAT` bit(1) DEFAULT NULL,
  `SEAT_NUMBER` int(11) DEFAULT NULL,
  `FRACTIONAL_UNIT` bit(1) DEFAULT NULL,
  `HAS_MODIIERS` bit(1) DEFAULT NULL,
  `PRINTED_TO_KITCHEN` bit(1) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `STOCK_AMOUNT_ADJUSTED` bit(1) DEFAULT NULL,
  `PIZZA_TYPE` bit(1) DEFAULT NULL,
  `SIZE_MODIFIER_ID` int(11) DEFAULT NULL,
  `TICKET_ID` int(11) DEFAULT NULL,
  `PG_ID` int(11) DEFAULT NULL,
  `PIZZA_SECTION_MODE` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK979F546633E5D3B2` (`SIZE_MODIFIER_ID`),
  KEY `FK979F54665CF1375F` (`PG_ID`),
  KEY `FK979F54661DF2D7F1` (`TICKET_ID`),
  CONSTRAINT `FK979F54661DF2D7F1` FOREIGN KEY (`TICKET_ID`) REFERENCES `ticket` (`ID`),
  CONSTRAINT `FK979F546633E5D3B2` FOREIGN KEY (`SIZE_MODIFIER_ID`) REFERENCES `ticket_item_modifier` (`ID`),
  CONSTRAINT `FK979F54665CF1375F` FOREIGN KEY (`PG_ID`) REFERENCES `printer_group` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item_addon_relation` */

DROP TABLE IF EXISTS `ticket_item_addon_relation`;

CREATE TABLE `ticket_item_addon_relation` (
  `TICKET_ITEM_ID` int(11) NOT NULL,
  `MODIFIER_ID` int(11) NOT NULL,
  `LIST_ORDER` int(11) NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TICKET_ITEM_ID`,`LIST_ORDER`),
  KEY `FK9F199634DEC6120A` (`TICKET_ITEM_ID`),
  KEY `FK9F1996346C108EF0` (`MODIFIER_ID`),
  CONSTRAINT `FK9F1996346C108EF0` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `ticket_item_modifier` (`ID`),
  CONSTRAINT `FK9F199634DEC6120A` FOREIGN KEY (`TICKET_ITEM_ID`) REFERENCES `ticket_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item_cooking_instruction` */

DROP TABLE IF EXISTS `ticket_item_cooking_instruction`;

CREATE TABLE `ticket_item_cooking_instruction` (
  `TICKET_ITEM_ID` int(11) NOT NULL,
  `description` varchar(60) DEFAULT NULL,
  `printedToKitchen` bit(1) DEFAULT NULL,
  `ITEM_ORDER` int(11) NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TICKET_ITEM_ID`,`ITEM_ORDER`),
  KEY `FK3825F9D0DEC6120A` (`TICKET_ITEM_ID`),
  CONSTRAINT `FK3825F9D0DEC6120A` FOREIGN KEY (`TICKET_ITEM_ID`) REFERENCES `ticket_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item_discount` */

DROP TABLE IF EXISTS `ticket_item_discount`;

CREATE TABLE `ticket_item_discount` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCOUNT_ID` int(11) DEFAULT NULL,
  `NAME` varchar(30) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `AUTO_APPLY` bit(1) DEFAULT NULL,
  `MINIMUM_QUANTITY` int(11) DEFAULT NULL,
  `VALUE` double DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `TICKET_ITEMID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK3DF5D4FAB9276E77` (`TICKET_ITEMID`),
  CONSTRAINT `FK3DF5D4FAB9276E77` FOREIGN KEY (`TICKET_ITEMID`) REFERENCES `ticket_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item_modifier` */

DROP TABLE IF EXISTS `ticket_item_modifier`;

CREATE TABLE `ticket_item_modifier` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) DEFAULT NULL,
  `GROUP_ID` int(11) DEFAULT NULL,
  `ITEM_COUNT` int(11) DEFAULT NULL,
  `MODIFIER_NAME` varchar(120) DEFAULT NULL,
  `MODIFIER_PRICE` double DEFAULT NULL,
  `MODIFIER_TAX_RATE` double DEFAULT NULL,
  `MODIFIER_TYPE` int(11) DEFAULT NULL,
  `SUBTOTAL_PRICE` double DEFAULT NULL,
  `TOTAL_PRICE` double DEFAULT NULL,
  `TAX_AMOUNT` double DEFAULT NULL,
  `INFO_ONLY` bit(1) DEFAULT NULL,
  `SECTION_NAME` varchar(20) DEFAULT NULL,
  `MULTIPLIER_NAME` varchar(20) DEFAULT NULL,
  `PRINT_TO_KITCHEN` bit(1) DEFAULT NULL,
  `SECTION_WISE_PRICING` bit(1) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `PRINTED_TO_KITCHEN` bit(1) DEFAULT NULL,
  `TICKET_ITEM_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK8FD6290DEC6120A` (`TICKET_ITEM_ID`),
  CONSTRAINT `FK8FD6290DEC6120A` FOREIGN KEY (`TICKET_ITEM_ID`) REFERENCES `ticket_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_item_modifier_relation` */

DROP TABLE IF EXISTS `ticket_item_modifier_relation`;

CREATE TABLE `ticket_item_modifier_relation` (
  `TICKET_ITEM_ID` int(11) NOT NULL,
  `MODIFIER_ID` int(11) NOT NULL,
  `LIST_ORDER` int(11) NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TICKET_ITEM_ID`,`LIST_ORDER`),
  KEY `FK5D3F9ACBDEC6120A` (`TICKET_ITEM_ID`),
  KEY `FK5D3F9ACB6C108EF0` (`MODIFIER_ID`),
  CONSTRAINT `FK5D3F9ACB6C108EF0` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `ticket_item_modifier` (`ID`),
  CONSTRAINT `FK5D3F9ACBDEC6120A` FOREIGN KEY (`TICKET_ITEM_ID`) REFERENCES `ticket_item` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_properties` */

DROP TABLE IF EXISTS `ticket_properties`;

CREATE TABLE `ticket_properties` (
  `id` int(11) NOT NULL,
  `property_value` text,
  `property_name` varchar(255) NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`,`property_name`),
  KEY `FK70ECD046223049DE` (`id`),
  CONSTRAINT `FK70ECD046223049DE` FOREIGN KEY (`id`) REFERENCES `ticket` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ticket_table_num` */

DROP TABLE IF EXISTS `ticket_table_num`;

CREATE TABLE `ticket_table_num` (
  `ticket_id` int(11) NOT NULL,
  `TABLE_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  KEY `FK65AF15E21DF2D7F1` (`ticket_id`),
  CONSTRAINT `FK65AF15E21DF2D7F1` FOREIGN KEY (`ticket_id`) REFERENCES `ticket` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `transaction_properties` */

DROP TABLE IF EXISTS `transaction_properties`;

CREATE TABLE `transaction_properties` (
  `id` int(11) NOT NULL,
  `property_value` varchar(255) DEFAULT NULL,
  `property_name` varchar(255) NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`,`property_name`),
  KEY `FKE3DE65548E8203BC` (`id`),
  CONSTRAINT `FKE3DE65548E8203BC` FOREIGN KEY (`id`) REFERENCES `transactions` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `transactions` */

DROP TABLE IF EXISTS `transactions`;

CREATE TABLE `transactions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PAYMENT_TYPE` varchar(30) NOT NULL,
  `GLOBAL_ID` varchar(16) DEFAULT NULL,
  `TRANSACTION_TIME` datetime DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `TIPS_AMOUNT` double DEFAULT NULL,
  `TIPS_EXCEED_AMOUNT` double DEFAULT NULL,
  `TENDER_AMOUNT` double DEFAULT NULL,
  `TRANSACTION_TYPE` varchar(30) NOT NULL,
  `CUSTOM_PAYMENT_NAME` varchar(60) DEFAULT NULL,
  `CUSTOM_PAYMENT_REF` varchar(120) DEFAULT NULL,
  `CUSTOM_PAYMENT_FIELD_NAME` varchar(60) DEFAULT NULL,
  `PAYMENT_SUB_TYPE` varchar(40) NOT NULL,
  `CAPTURED` bit(1) DEFAULT NULL,
  `VOIDED` bit(1) DEFAULT NULL,
  `AUTHORIZABLE` bit(1) DEFAULT NULL,
  `CARD_HOLDER_NAME` varchar(60) DEFAULT NULL,
  `CARD_NUMBER` varchar(40) DEFAULT NULL,
  `CARD_AUTH_CODE` varchar(30) DEFAULT NULL,
  `CARD_TYPE` varchar(20) DEFAULT NULL,
  `CARD_TRANSACTION_ID` varchar(255) DEFAULT NULL,
  `CARD_MERCHANT_GATEWAY` varchar(60) DEFAULT NULL,
  `CARD_READER` varchar(30) DEFAULT NULL,
  `CARD_AID` varchar(120) DEFAULT NULL,
  `CARD_ARQC` varchar(120) DEFAULT NULL,
  `CARD_EXT_DATA` varchar(255) DEFAULT NULL,
  `GIFT_CERT_NUMBER` varchar(64) DEFAULT NULL,
  `GIFT_CERT_FACE_VALUE` double DEFAULT NULL,
  `GIFT_CERT_PAID_AMOUNT` double DEFAULT NULL,
  `GIFT_CERT_CASH_BACK_AMOUNT` double DEFAULT NULL,
  `DRAWER_RESETTED` bit(1) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  `TERMINAL_ID` int(11) DEFAULT NULL,
  `TICKET_ID` int(11) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `PAYOUT_REASON_ID` int(11) DEFAULT NULL,
  `PAYOUT_RECEPIENT_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GLOBAL_ID` (`GLOBAL_ID`),
  KEY `tran_drawer_resetted` (`DRAWER_RESETTED`),
  KEY `FKFE9871553E20AD51` (`USER_ID`),
  KEY `FKFE987155FC697D9E` (`PAYOUT_REASON_ID`),
  KEY `FKFE987155CA43B6` (`PAYOUT_RECEPIENT_ID`),
  KEY `FKFE9871551DF2D7F1` (`TICKET_ID`),
  KEY `FKFE9871552AD2D031` (`TERMINAL_ID`),
  CONSTRAINT `FKFE9871551DF2D7F1` FOREIGN KEY (`TICKET_ID`) REFERENCES `ticket` (`ID`),
  CONSTRAINT `FKFE9871552AD2D031` FOREIGN KEY (`TERMINAL_ID`) REFERENCES `terminal` (`ID`),
  CONSTRAINT `FKFE9871553E20AD51` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`AUTO_ID`),
  CONSTRAINT `FKFE987155CA43B6` FOREIGN KEY (`PAYOUT_RECEPIENT_ID`) REFERENCES `payout_recepients` (`ID`),
  CONSTRAINT `FKFE987155FC697D9E` FOREIGN KEY (`PAYOUT_REASON_ID`) REFERENCES `payout_reasons` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `user_menu` */

DROP TABLE IF EXISTS `user_menu`;

CREATE TABLE `user_menu` (
  `NAME` varchar(40) DEFAULT NULL,
  `MENU_ID` int(11) NOT NULL,
  PRIMARY KEY (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `user_permission` */

DROP TABLE IF EXISTS `user_permission`;

CREATE TABLE `user_permission` (
  `permissionId` int(11) DEFAULT NULL,
  `ID` int(11) NOT NULL,
  `MENU_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK2DBEAA4F283ECC6` (`permissionId`),
  KEY `FK_user_permission` (`MENU_ID`),
  CONSTRAINT `FK_user_permission` FOREIGN KEY (`MENU_ID`) REFERENCES `user_menu` (`MENU_ID`),
  CONSTRAINT `FK2DBEAA4F283ECC6` FOREIGN KEY (`permissionId`) REFERENCES `user_type` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `user_type` */

DROP TABLE IF EXISTS `user_type`;

CREATE TABLE `user_type` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `P_NAME` varchar(60) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `AUTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `USER_PASS` varchar(16) NOT NULL,
  `FIRST_NAME` varchar(30) DEFAULT NULL,
  `LAST_NAME` varchar(30) DEFAULT NULL,
  `SSN` varchar(30) DEFAULT NULL,
  `COST_PER_HOUR` double DEFAULT NULL,
  `CLOCKED_IN` bit(1) DEFAULT NULL,
  `LAST_CLOCK_IN_TIME` datetime DEFAULT NULL,
  `LAST_CLOCK_OUT_TIME` datetime DEFAULT NULL,
  `PHONE_NO` varchar(20) DEFAULT NULL,
  `IS_DRIVER` bit(1) DEFAULT NULL,
  `AVAILABLE_FOR_DELIVERY` bit(1) DEFAULT NULL,
  `ACTIVE` bit(1) DEFAULT NULL,
  `SHIFT_ID` int(11) DEFAULT NULL,
  `currentTerminal` int(11) DEFAULT NULL,
  `N_USER_TYPE` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `ORG_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AUTO_ID`),
  UNIQUE KEY `USER_PASS` (`USER_PASS`),
  UNIQUE KEY `USER_ID` (`USER_ID`),
  KEY `FK4D495E87660A5E3` (`SHIFT_ID`),
  KEY `FK4D495E8D9409968` (`currentTerminal`),
  KEY `FK4D495E8897B1E39` (`N_USER_TYPE`),
  CONSTRAINT `FK4D495E87660A5E3` FOREIGN KEY (`SHIFT_ID`) REFERENCES `shift` (`ID`),
  CONSTRAINT `FK4D495E8897B1E39` FOREIGN KEY (`N_USER_TYPE`) REFERENCES `user_type` (`ID`),
  CONSTRAINT `FK4D495E8D9409968` FOREIGN KEY (`currentTerminal`) REFERENCES `terminal` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Table structure for table `virtual_printer` */

DROP TABLE IF EXISTS `virtual_printer`;

CREATE TABLE `virtual_printer` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(60) NOT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `virtualprinter_order_type` */

DROP TABLE IF EXISTS `virtualprinter_order_type`;

CREATE TABLE `virtualprinter_order_type` (
  `printer_id` int(11) NOT NULL,
  `ORDER_TYPE` varchar(255) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  KEY `FK9AF7853BCF15F4A6` (`printer_id`),
  CONSTRAINT `FK9AF7853BCF15F4A6` FOREIGN KEY (`printer_id`) REFERENCES `virtual_printer` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `void_reasons` */

DROP TABLE IF EXISTS `void_reasons`;

CREATE TABLE `void_reasons` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REASON_TEXT` varchar(255) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `zip_code_vs_delivery_charge` */

DROP TABLE IF EXISTS `zip_code_vs_delivery_charge`;

CREATE TABLE `zip_code_vs_delivery_charge` (
  `AUTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ZIP_CODE` varchar(10) NOT NULL,
  `DELIVERY_CHARGE` double NOT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
